variables:
  GIT_SUBMODULE_STRATEGY: none

# Test that the git version of RSG compiles with various versions of SimGrid docker image
.build_git: &build_git
  script:
    - apt-get update
    - apt-get install -y cmake build-essential libzmq3-dev libthrift-dev thrift-compiler libboost-dev libboost-program-options-dev
    - cmake . -DCMAKE_BUILD_TYPE=Debug -Denable_warnings=ON -Dtreat_warnings_as_errors=OFF
    - make -j $(nproc) VERBOSE=1
    - export LC_ALL='en_US.UTF-8' && ctest --output-on-failure -E 'actor_kill_pid|turnon_turnoff'

test-git-unstable:
  image: simgrid/unstable
  <<: *build_git

test-git-v3.22:
  image: simgrid/stable:v3.22.2
  <<: *build_git

test-git-v3.21:
  image: simgrid/stable:v3_21
  <<: *build_git

#test-git-v3.20:
#  image: simgrid/stable:v3.20
#  <<: *build_git
